part of excel;

enum FontFamily {
  Al_Bayan_Plain,
  Abadi_MT_Condensed_Light,
  Abadi_MT_Condensed_Extra_Bold,
  Al_Nile,
  Al_Tarikh_Regular,
  American_Typewriter,
  Andale_Mono,
  Angsana_New,
  Apple_Braille_Outline_8_Dot,
  Apple_Chancery,
  Apple_Color_Emoji,
  Apple_Symbols,
  Arial,
  Arial_Hebrew,
  Arial_Hebrew_Scholar,
  Arial_Narrow,
  Arial_Rounded_MT_Bold,
  Arial_Unicode_MS,
  Athelas_Regular,
  Avenir_Book,
  Avenir_Next_Regular,
  Avenir_Next_Condensed_Regular,
  Ayuthaya,
  Baghdad,
  Bangla_MN,
  Bangla_Sangam_MN,
  Baskerville,
  Baskerville_Old_Face,
  Bauhaus_93,
  Beirut,
  Bell_MT,
  Bernard_MT_Condensed,
  Big_Caslon,
  Bodoni_72,
  Bodoni_72_Oldstyle,
  Bodoni_72_Smallcaps,
  Bodoni_Ornaments,
  Book_Antiqua,
  Bookman_Old_Style,
  Bookshelf_Symbol_7,
  Bradley_Hand,
  Braggadocio,
  Britannic_Bold,
  Brush_Script_MT,
  Calibri,
  Calisto_MT,
  Cambria,
  Cambria_Math,
  Candara,
  Century,
  Century_Gothic,
  Century_Schoolbook,
  Chalkboard,
  Chalkboard_SE,
  Chalkduster,
  Charter,
  Cochin,
  Colonna_MT,
  Comic_Sans_MS,
  Consolas,
  Constantia,
  Cooper_Black,
  Copperplate,
  Copperplate_Gothic_Bold,
  Corbel,
  Cordia_New,
  CordiaUPC,
  Corsiva_Hebrew,
  Courier,
  Courier_New,
  Curlz_MT,
  Damascus,
  David,
  DecoType_Naskh,
  Desdemona,
  Devanagari_MT,
  Devanagari_Sangam_MN,
  Didot,
  DIN_Alternate,
  DIN_Condensed,
  Diwan_Kufi,
  Diwan_Thuluth,
  Dubai,
  Edwardian_Script_ITC,
  Engravers_MT,
  Euphemia_UCAS,
  Eurostile,
  Farah,
  Farisi,
  Footlight_MT_Light,
  Franklin_Gothic_Book,
  Franklin_Gothic_Demi,
  Franklin_Gothic_Demi_Cond,
  Franklin_Gothic_Heavy,
  Franklin_Gothic_Medium,
  Franklin_Gothic_Medium_Cond,
  Futura,
  Gabriola,
  Galvji,
  Garamond,
  Gautami,
  Geeza_Pro,
  Geneva,
  Georgia,
  Gill_Sans,
  Gill_Sans_MT,
  Gill_Sans_MT_Condensed,
  Gill_Sans_MT_Ext_Condensed_Bold,
  Gill_Sans_Ultra_Bold,
  Gloucester_MT_Extra_Condensed,
  Goudy_Old_Style,
  Gujarati_MT,
  Gujarati_Sangam_MN,
  Gurmukhi_MN,
  Gurmukhi_MT,
  Gurmukhi_Sangam_MN,
  Haettenschweiler,
  Harrington,
  Helvetica,
  Helvetica_Neue,
  Herculanum,
  Hoefler_Text,
  Impact,
  Imprint_MT_Shadow,
  InaiMathi,
  Iowan_Old_Style,
  ITF_Devanagari,
  ITF_Devanagari_Marathi,
  Kailasa,
  Kannada_MN,
  Kannada_Sangam_MN,
  Kartika,
  Kefa,
  Khmer_MN,
  Khmer_Sangam_MN,
  Kino_MT,
  Kohinoor_Bangla,
  Kohinoor_Devanagari,
  Kohinoor_Gujarati,
  Kohinoor_Telugu,
  Kokonor,
}

List<String> _fontFamilyStorage = [
  "Al Bayan Plain",
  "Abadi MT Condensed Light",
  "Abadi MT Condensed Extra Bold",
  "Al Nile",
  "Al Tarikh Regular",
  "American Typewriter",
  "Andale Mono",
  "Angsana New",
  "Apple Braille Outline 8 Dot",
  "Apple Chancery",
  "Apple Color Emoji",
  "Apple Symbols",
  "Arial",
  "Arial Hebrew",
  "Arial Hebrew Scholar",
  "Arial Narrow",
  "Arial Rounded MT Bold",
  "Arial Unicode MS",
  "Athelas Regular",
  "Avenir Book",
  "Avenir Next Regular",
  "Avenir Next Condensed Regular",
  "Ayuthaya",
  "Baghdad",
  "Bangla MN",
  "Bangla Sangam MN",
  "Baskerville",
  "Baskerville Old Face",
  "Bauhaus 93",
  "Beirut",
  "Bell MT",
  "Bernard MT Condensed",
  "Big Caslon",
  "Bodoni 72",
  "Bodoni 72 Oldstyle",
  "Bodoni 72 Smallcaps",
  "Bodoni Ornaments",
  "Book Antiqua",
  "Bookman Old Style",
  "Bookshelf Symbol 7",
  "Bradley Hand",
  "Braggadocio",
  "Britannic Bold",
  "Brush Script MT",
  "Calibri",
  "Calisto MT",
  "Cambria",
  "Cambria Math",
  "Candara",
  "Century",
  "Century Gothic",
  "Century Schoolbook",
  "Chalkboard",
  "Chalkboard SE",
  "Chalkduster",
  "Charter",
  "Cochin",
  "Colonna MT",
  "Comic Sans MS",
  "Consolas",
  "Constantia",
  "Cooper Black",
  "Copperplate",
  "Copperplate Gothic Bold",
  "Corbel",
  "Cordia New",
  "CordiaUPC",
  "Corsiva Hebrew",
  "Courier",
  "Courier New",
  "Curlz MT",
  "Damascus",
  "David",
  "DecoType Naskh",
  "Desdemona",
  "Devanagari MT",
  "Devanagari Sangam MN",
  "Didot",
  "DIN Alternate",
  "DIN Condensed",
  "Diwan Kufi",
  "Diwan Thuluth",
  "Dubai",
  "Edwardian Script ITC",
  "Engravers MT",
  "Euphemia UCAS",
  "Eurostile",
  "Farah",
  "Farisi",
  "Footlight MT Light",
  "Franklin Gothic Book",
  "Franklin Gothic Demi",
  "Franklin Gothic Demi Cond",
  "Franklin Gothic Heavy",
  "Franklin Gothic Medium",
  "Franklin Gothic Medium Cond",
  "Futura",
  "Gabriola",
  "Galvji",
  "Garamond",
  "Gautami",
  "Geeza Pro",
  "Geneva",
  "Georgia",
  "Gill Sans",
  "Gill Sans MT",
  "Gill Sans MT Condensed",
  "Gill Sans MT Ext Condensed Bold",
  "Gill Sans Ultra Bold",
  "Gloucester MT Extra Condensed",
  "Goudy Old Style",
  "Gujarati MT",
  "Gujarati Sangam MN",
  "Gurmukhi MN",
  "Gurmukhi MT",
  "Gurmukhi Sangam MN",
  "Haettenschweiler",
  "Harrington",
  "Helvetica",
  "Helvetica Neue",
  "Herculanum",
  "Hoefler Text",
  "Impact",
  "Imprint MT Shadow",
  "InaiMathi",
  "Iowan Old Style",
  "ITF Devanagari",
  "ITF Devanagari Marathi",
  "Kailasa",
  "Kannada MN",
  "Kannada Sangam MN",
  "Kartika",
  "Kefa",
  "Khmer MN",
  "Khmer Sangam MN",
  "Kino MT",
  "Kohinoor Bangla",
  "Kohinoor Devanagari",
  "Kohinoor Gujarati",
  "Kohinoor Telugu",
  "Kokonor",
];

/* void check_it() {
  int len = FontFamily.values.length;
  print("len1: " + len.toString());
  List<FontFamily> family = FontFamily.values;
  print("len2: " + family.length.toString());
  for (int i = 0; i < _fontFamilyStorage.length; i++) {
    if (i < len) {
      if (family[i].toString().replaceAll("_", " ") ==
          "FontFamily." + _fontFamilyStorage[i]) {
        print("true");
      } else {
        print(family[i].toString());
      }
    }
  }
} */

/**
 * 
 * returns the `Font Family Name`
 * 
 */
String getFontFamily(FontFamily fontFamily) {
  return _fontFamilyStorage[FontFamily.values.indexOf(fontFamily)];
}
