part of excel;

enum FontFamily {
  Al_Bayan_Plain,
  Abadi_MT_Condensed_Light,
  Abadi_MT_Condensed_Extra_Bold,
  Al_Nile,
  Al_Tarikh_Regular,
  American_Typewriter,
  Andale_Mono,
  Angsana_New,
  Apple_Braille_Outline_8_Dot,
  Apple_Chancery,
  Apple_Color_Emoji,
  Apple_Symbols,
  Arial,
  Arial_Hebre,
  Arial_Hebrew_Scholar,
  Arial_Narrow,
  Arial_Rounded_MT_Bold,
  Arial_Unicode_MS,
  Athelas_Regular,
  Avenir_Book,
  Avenir_Next_Regular,
  Avenir_Next_Condensed_Regular,
  Ayuthaya,
  Baghdad,
  Bangla_MN,
  Bangla_Sangam_MN,
  Baskerville,
  Baskerville_Old_Face,
  Bauhaus_93,
  Beirut,
  Bell_MT,
  Bernard_MT_Condensed,
  Big_Caslon,
  Bodoni_72,
  Bodoni_72_Oldstyle,
  Bodoni_72_Smallcaps,
  Bodoni_Ornaments,
  Book_Antiqua,
  Bookman_Old_Style,
  Bookshelf_Symbol_7,
  Bradley_Hand,
  Braggadocio,
  Britannic_Bold,
  Brush_Script_MT,
  Calibri,
  Calisto_MT,
  Cambria,
  Cambria_Math,
  Candara,
  Century,
  Century_Gothic,
  Century_Schoolbook,
  Chalkboard,
  Chalkboard_SE,
  Chalkduster,
  Charter,
  Cochin,
  Colonna_MT,
  Comic_Sans_MS,
  Consolas,
  Constantia,
  Cooper_Black,
  Copperplate,
  Copperplate_Gothic_Bold,
  Corbel,
  Cordia_New,
  CordiaUPC,
  Corsiva_Hebrew,
  Courier,
  Courier_New,
  Curlz_MT,
}

List<String> _fontFamiltStorage = [
  "Al Bayan Plain",
  "Abadi MT Condensed Light",
  "Abadi MT Condensed Extra Bold",
  "Al Nile",
  "Al Tarikh Regular",
  "American Typewriter",
  "Andale Mono",
  "Angsana New",
  "Apple Braille Outline 8 Dot",
  "Apple Chancery",
  "Apple Color Emoji",
  "Apple Symbols",
  "Arial",
  "Arial Hebrew",
  "Arial Hebrew Scholar",
  "Arial Narrow",
  "Arial Rounded MT Bold",
  "Arial Unicode MS",
  "Athelas Regular",
  "Avenir Book",
  "Avenir Next Regular",
  "Avenir Next Condensed Regular",
  "Ayuthaya",
  "Baghdad",
  "Bangla MN",
  "Bangla Sangam MN",
  "Baskerville",
  "Baskerville Old Face",
  "Bauhaus 93",
  "Beirut",
  "Bell MT",
  "Bernard MT Condensed",
  "Big Caslon",
  "Bodoni 72",
  "Bodoni 72 Oldstyle",
  "Bodoni 72 Smallcaps",
  "Bodoni Ornaments",
  "Book Antiqua",
  "Bookman Old Style",
  "Bookshelf Symbol 7",
  "Bradley Hand",
  "Braggadocio",
  "Britannic Bold",
  "Brush Script MT",
  "Calibri",
  "Calisto MT",
  "Cambria",
  "Cambria Math",
  "Candara",
  "Century",
  "Century Gothic",
  "Century Schoolbook",
  "Chalkboard",
  "Chalkboard SE",
  "Chalkduster",
  "Charter",
  "Cochin",
  "Colonna MT",
  "Comic Sans MS",
  "Consolas",
  "Constantia",
  "Cooper Black",
  "Copperplate",
  "Copperplate Gothic Bold",
  "Corbel",
  "Cordia New",
  "CordiaUPC",
  "Corsiva Hebrew",
  "Courier",
  "Courier New",
  "Curlz MT",
];

/**
 * 
 * returns the `Font Family Name`
 * 
 */
String getFontFamily(FontFamily fontFamily) {
  return _fontFamiltStorage[FontFamily.values.indexOf(fontFamily)];
}
